"""empty message

Revision ID: ab7025289c64
Revises: c746033e50b0
Create Date: 2017-08-11 16:07:38.080754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7025289c64'
down_revision = 'c746033e50b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dtc_projects', sa.Column('icon', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dtc_projects', 'icon')
    # ### end Alembic commands ###
