"""empty message

Revision ID: b9540855a1ba
Revises: c0cedac8056c
Create Date: 2017-08-14 17:25:20.178837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9540855a1ba'
down_revision = 'c0cedac8056c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'education')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('education', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
