"""empty message

Revision ID: c0cedac8056c
Revises: ab7025289c64
Create Date: 2017-08-14 12:31:43.845226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0cedac8056c'
down_revision = 'ab7025289c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aim', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('edit_required', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('education', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('field', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('ip', sa.String(length=15), nullable=True))
    op.add_column('users', sa.Column('major', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('org', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('realname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'realname')
    op.drop_column('users', 'org')
    op.drop_column('users', 'major')
    op.drop_column('users', 'ip')
    op.drop_column('users', 'field')
    op.drop_column('users', 'education')
    op.drop_column('users', 'edit_required')
    op.drop_column('users', 'country')
    op.drop_column('users', 'aim')
    # ### end Alembic commands ###
