"""empty message

Revision ID: c746033e50b0
Revises: e539793d2347
Create Date: 2017-08-11 14:33:24.203828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c746033e50b0'
down_revision = 'e539793d2347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dtc_projects', sa.Column('previews', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dtc_projects', 'previews')
    # ### end Alembic commands ###
