"""empty message

Revision ID: e539793d2347
Revises: 
Create Date: 2017-08-09 16:40:37.190467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e539793d2347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dtc_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('project_dir', sa.Text(), nullable=True),
    sa.Column('classified_pictures', sa.Text(), nullable=True),
    sa.Column('training_pictures', sa.Text(), nullable=True),
    sa.Column('training_pic_kinds', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dtc_projects_project_name'), 'dtc_projects', ['project_name'], unique=False)
    op.create_index(op.f('ix_dtc_projects_timestamp'), 'dtc_projects', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dtc_projects_timestamp'), table_name='dtc_projects')
    op.drop_index(op.f('ix_dtc_projects_project_name'), table_name='dtc_projects')
    op.drop_table('dtc_projects')
    # ### end Alembic commands ###
